### ISSUE TITLE
License? Maplibre conversion/extension?

### ISSUE THREAD

**Issue by ezadoo** [meijer3/mapbox-imdf#10]
What’s the license of this repository?

As Mapbox has revoked their OpenSource-License for mapbox-gl, is there a chance that the imdf functionality could be converted to or even integrated in maplibre?

But as there is no license included nobody could do something like that without potential risks with copyright infringement or something like that.

**Comment by meijer3** [comment]
I assume so, I dont have time to look in to this right now, but feel free to create a PR, of fork the project

**Comment by ezadoo** [comment]
That's why I'm also asking for the license.

If you could add one (MIT, GPL , etc (or The Unlicense if you want public domain)), this would help me, or in general if somebody is willing to work on this too.

**Comment by meijer3** [comment]
I added the MIT License
